// Regenerates both SVG wordmarks from src/ansi.mjs's BANNER_LINES, so the
// README banner, the holding page and the CLI banner can never show different
// art. Run after changing the art:
//
//   node tools/wordmark.mjs
//
// Outputs:
//   docs/wordmark.svg         — <rect> per run, used by README.md
//   docs/wordmark-inline.svg  — single <path>, small enough to embed; paste
//                               into template/.claude/commands/verify.md
//
// The holding page embeds its own copy rather than linking a file (a scaffolded
// site has no access to this repo). test/agent-files.test.mjs rebuilds the
// glyph grid from that copy's path data and diffs it against the art, so a
// forgotten paste fails the suite rather than shipping a stale wordmark.
//
// Rendered as geometry, never as <text>: SVG text depends on the viewer having
// a monospace font whose glyph widths match the character advance. That
// assumption was tested and found false — see the fix that replaced the
// text-based wordmark on the holding page.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const repo = (rel) => fileURLToPath(new URL(`../${rel}`, import.meta.url));

const art = (await readFile(repo('src/ansi.mjs'), 'utf8'))
  .split('\n')
  .filter((l) => l.includes('█'))
  .map((l) => l.match(/'(.*)'/)[1]);

if (art.length !== 5) throw new Error(`expected 5 art rows in src/ansi.mjs, found ${art.length}`);

/** Merge horizontal runs of blocks so letters render as strokes, not grids of squares. */
function runs(cell, row) {
  const out = [];
  art.forEach((line, y) => {
    let n = 0;
    for (let x = 0; x <= line.length; x++) {
      if (line[x] === '█') { n++; continue; }
      if (n > 0) { out.push({ x: (x - n) * cell, y: y * row, w: n * cell }); n = 0; }
    }
  });
  return out;
}

const cols = Math.max(...art.map((l) => l.length));
await mkdir(repo('docs'), { recursive: true });

// --- README banner: padded, one rect per run, easy to read and tweak.
{
  const CELL = 9, ROW = 13, PAD = 4;
  const w = cols * CELL + PAD * 2;
  const h = art.length * ROW + PAD * 2;
  const rects = runs(CELL, ROW)
    .map((r) => `  <rect x="${r.x + PAD}" y="${r.y + PAD}" width="${r.w}" height="${ROW - 2}" fill="#ff2d78"/>`)
    .join('\n');
  await writeFile(
    repo('docs/wordmark.svg'),
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="AgentPress">
  <title>AgentPress</title>
  <!-- Generated by tools/wordmark.mjs from src/ansi.mjs. Do not hand-edit. -->
${rects}
</svg>
`,
    'utf8',
  );
  console.log(`docs/wordmark.svg        ${w}x${h}`);
}

// --- Embeddable: one path, no padding, sized by CSS at the call site.
{
  const CELL = 10, ROW = 14, GAP = 2;
  const d = runs(CELL, ROW).map((r) => `M${r.x} ${r.y}h${r.w}v${ROW - GAP}h-${r.w}z`).join('');
  const w = cols * CELL;
  const h = art.length * ROW - GAP;
  const svg = `<svg class="ap-mark" viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="AgentPress"><path d="${d}" fill="#ff2d78"/></svg>`;
  await writeFile(repo('docs/wordmark-inline.svg'), `${svg}\n`, 'utf8');
  console.log(`docs/wordmark-inline.svg ${svg.length} bytes — paste into verify.md if the art changed`);
}
